name: AutoMessage
author: ELCHILEN0
description: Easily schedule configurable server wide broadcasts!
version: 2.0.0
website: http://www.novuscraft.org
main: com.JnaniDev.AutoMessage.AutoMessage
commands:
   automessage:
     description: Main command for all AutoMessage commands
     aliases: [automsg, am]
permissions:
   automessage.reload:
     description: Permission to reload the configuration from the disk.
   automessage.messages.add:
     description: Permission to add messages.
   automessage.messages.remove:
     description: Permission to remove messages.
   automessage.messages.list:
     description: Permission to list the messages and their indexes.
   automessage.messages.broadcast:
     description: Permission to broadcast a message by index.
   automessage.messages.edit:
     description: Permission to edit a message by index.
   automessage.config.interval:
     description: Permission to set the broadcast interval.
   automessage.config.prefix:
     description: Permission to set the broadcast prefix.
   automessage.config.random:
     description: Permission to toggle randomized message order.
   automessage.config.logToConsole:
     description: Permission to toggle logging to console
   automessage.config.enabled:
     description: Permission to enable or disable broadcasting.